backend:
  name: git-gateway
  repo: dev-rakibul1/hairbar # Path to your Github repository
  branch: main # Branch to update (master by default)

media_folder: "public/img" # Folder where user uploaded files should go
public_folder: "/img" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: contents
    label: news
    folder: src/contents/news
    create: true
    fields:
      - { name: comment, label: comment, widget: string }
      - { name: title, label: title, widget: string }
